import type { Club, Competition, Stadium } from "@/types/football";

/**
 * Competitions, stadiums and clubs — the reference data every fixture
 * source joins against. Kept apart from the fixture seeds so an imported
 * season (premierLeagueSeason.ts) and the hand-written seeds (mockData.ts)
 * can both use it without importing each other.
 */

export const competitions: Record<string, Competition> = {
  premier_league: {
    id: "PL",
    slug: "premier-league",
    name: "Premier League",
    shortName: "PL",
    country: "England",
    logo: "",
    color: "#3D195B",
  },
  la_liga: {
    id: "PD",
    slug: "la-liga",
    name: "La Liga",
    shortName: "La Liga",
    country: "Spain",
    logo: "",
    color: "#EE8707",
  },
  serie_a: {
    id: "SA",
    slug: "serie-a",
    name: "Serie A",
    shortName: "Serie A",
    country: "Italy",
    logo: "",
    color: "#008FD7",
  },
  bundesliga: {
    id: "BL1",
    slug: "bundesliga",
    name: "Bundesliga",
    shortName: "Bundesliga",
    country: "Germany",
    logo: "",
    color: "#D20515",
  },
  ligue_1: {
    id: "FL1",
    slug: "ligue-1",
    name: "Ligue 1",
    shortName: "Ligue 1",
    country: "France",
    logo: "",
    color: "#0A2B5E",
  },
  champions_league: {
    id: "CL",
    slug: "champions-league",
    name: "UEFA Champions League",
    shortName: "UCL",
    country: "Europe",
    logo: "",
    color: "#0E1E5B",
  },
  europa_league: {
    id: "EL",
    slug: "europa-league",
    name: "UEFA Europa League",
    shortName: "UEL",
    country: "Europe",
    logo: "",
    color: "#F97316",
  },
};

export const stadiums: Record<string, Stadium> = {
  emirates: {
    id: "st-emirates",
    slug: "emirates-stadium",
    name: "Emirates Stadium",
    city: "London",
    country: "England",
    capacity: 60704,
  },
  stamford_bridge: {
    id: "st-stamford-bridge",
    slug: "stamford-bridge",
    name: "Stamford Bridge",
    city: "London",
    country: "England",
    capacity: 40343,
  },
  anfield: {
    id: "st-anfield",
    slug: "anfield",
    name: "Anfield",
    city: "Liverpool",
    country: "England",
    capacity: 61276,
  },
  etihad: {
    id: "st-etihad",
    slug: "etihad-stadium",
    name: "Etihad Stadium",
    city: "Manchester",
    country: "England",
    capacity: 53400,
  },
  old_trafford: {
    id: "st-old-trafford",
    slug: "old-trafford",
    name: "Old Trafford",
    city: "Manchester",
    country: "England",
    capacity: 74310,
  },
  tottenham_hotspur: {
    id: "st-tottenham",
    slug: "tottenham-hotspur-stadium",
    name: "Tottenham Hotspur Stadium",
    city: "London",
    country: "England",
    capacity: 62850,
  },
  st_james_park: {
    id: "st-james-park",
    slug: "st-james-park",
    name: "St James' Park",
    city: "Newcastle",
    country: "England",
    capacity: 52305,
  },
  bernabeu: {
    id: "st-bernabeu",
    slug: "santiago-bernabeu",
    name: "Santiago Bernabéu",
    city: "Madrid",
    country: "Spain",
    capacity: 78297,
  },
  spotify_camp_nou: {
    id: "st-camp-nou",
    slug: "spotify-camp-nou",
    name: "Spotify Camp Nou",
    city: "Barcelona",
    country: "Spain",
    capacity: 48000,
  },
  metropolitano: {
    id: "st-metropolitano",
    slug: "civitas-metropolitano",
    name: "Civitas Metropolitano",
    city: "Madrid",
    country: "Spain",
    capacity: 70460,
  },
  san_siro: {
    id: "st-san-siro",
    slug: "san-siro",
    name: "San Siro",
    city: "Milan",
    country: "Italy",
    capacity: 75923,
  },
  allianz_stadium_turin: {
    id: "st-allianz-turin",
    slug: "allianz-stadium",
    name: "Allianz Stadium",
    city: "Turin",
    country: "Italy",
    capacity: 41507,
  },
  olimpico: {
    id: "st-olimpico",
    slug: "stadio-olimpico",
    name: "Stadio Olimpico",
    city: "Rome",
    country: "Italy",
    capacity: 70634,
  },
  maradona: {
    id: "st-maradona",
    slug: "diego-armando-maradona",
    name: "Diego Armando Maradona",
    city: "Naples",
    country: "Italy",
    capacity: 54726,
  },
  allianz_arena: {
    id: "st-allianz-arena",
    slug: "allianz-arena",
    name: "Allianz Arena",
    city: "Munich",
    country: "Germany",
    capacity: 75024,
  },
  signal_iduna_park: {
    id: "st-signal-iduna",
    slug: "signal-iduna-park",
    name: "Signal Iduna Park",
    city: "Dortmund",
    country: "Germany",
    capacity: 81365,
  },
  red_bull_arena_leipzig: {
    id: "st-red-bull-arena",
    slug: "red-bull-arena-leipzig",
    name: "Red Bull Arena",
    city: "Leipzig",
    country: "Germany",
    capacity: 47069,
  },
  parc_des_princes: {
    id: "st-parc-des-princes",
    slug: "parc-des-princes",
    name: "Parc des Princes",
    city: "Paris",
    country: "France",
    capacity: 47929,
  },
  velodrome: {
    id: "st-velodrome",
    slug: "orange-velodrome",
    name: "Orange Vélodrome",
    city: "Marseille",
    country: "France",
    capacity: 67394,
  },
  louis_ii: {
    id: "st-louis-ii",
    slug: "stade-louis-ii",
    name: "Stade Louis II",
    city: "Monaco",
    country: "Monaco",
    capacity: 16360,
  },

  // UEFA Champions League 2026/27 venues that no domestic league above
  // already covers. Names, cities and capacities are UEFA's own records for
  // these fixtures (scripts/import-champions-league-fixtures.ts), which is
  // why some read differently from the domestic listing: UEFA drops club
  // sponsor names from venue titles, and publishes the capacity available
  // for its own matches rather than the league one.
  aek_arena: { id: "st-aek-arena", slug: "aek-arena", name: "AEK Arena", city: "Athens", country: "Greece", capacity: 31100 },
  ali_sami_yen: { id: "st-ali-sami-yen", slug: "ali-sami-yen-spor-kompleksi", name: "Ali Sami Yen Spor Kompleksi", city: "Istanbul", country: "Turkey", capacity: 53387 },
  arena_stuttgart: { id: "st-arena-stuttgart", slug: "arena-stuttgart", name: "Arena Stuttgart", city: "Stuttgart", country: "Germany", capacity: 48833 },
  aspmyra: { id: "st-aspmyra", slug: "aspmyra", name: "Aspmyra", city: "Bodø", country: "Norway", capacity: 7342 },
  baku_olympic: { id: "st-baku-olympic", slug: "baku-olympic-stadium", name: "Baku Olympic Stadium", city: "Baku", country: "Azerbaijan", capacity: 68700 },
  bollaert_delelis: { id: "st-bollaert-delelis", slug: "stade-bollaert-delelis", name: "Stade Bollaert-Delelis", city: "Lens", country: "France", capacity: 27180 },
  de_kuip: { id: "st-de-kuip", slug: "stadion-feijenoord-de-kuip", name: "Stadion Feijenoord 'De Kuip'", city: "Rotterdam", country: "Netherlands", capacity: 48100 },
  do_dragao: { id: "st-do-dragao", slug: "estadio-do-dragao", name: "Estádio do Dragão", city: "Porto", country: "Portugal", capacity: 50033 },
  eden_arena: { id: "st-eden-arena", slug: "eden-arena", name: "Eden Arena", city: "Prague", country: "Czechia", capacity: 19370 },
  jan_breydel: { id: "st-jan-breydel", slug: "jan-breydelstadion", name: "Jan Breydelstadion", city: "Bruges", country: "Belgium", capacity: 28288 },
  jose_alvalade: { id: "st-jose-alvalade", slug: "estadio-jose-alvalade", name: "Estádio José Alvalade", city: "Lisbon", country: "Portugal", capacity: 52707 },
  la_cartuja: { id: "st-la-cartuja", slug: "la-cartuja-de-sevilla", name: "La Cartuja de Sevilla", city: "Seville", country: "Spain", capacity: 67717 },
  la_ceramica: { id: "st-la-ceramica", slug: "estadio-de-la-ceramica", name: "Estadio de la Cerámica", city: "Villarreal", country: "Spain", capacity: 21332 },
  narodny_futbalovy: { id: "st-narodny-futbalovy", slug: "narodny-futbalovy-stadion", name: "Národný futbalový štadión", city: "Bratislava", country: "Slovakia", capacity: 22750 },
  oberosterreich_arena: { id: "st-oberosterreich-arena", slug: "oberosterreich-arena", name: "Oberösterreich Arena", city: "Linz", country: "Austria", capacity: 12662 },
  pierre_mauroy: { id: "st-pierre-mauroy", slug: "stade-pierre-mauroy", name: "Stade Pierre Mauroy", city: "Villeneuve d'Ascq", country: "France", capacity: 49966 },
  psv_stadion: { id: "st-psv-stadion", slug: "psv-stadion", name: "PSV Stadion", city: "Eindhoven", country: "Netherlands", capacity: 32043 },
  sinigaglia: { id: "st-sinigaglia", slug: "giuseppe-sinigaglia", name: "Giuseppe Sinigaglia", city: "Como", country: "Italy", capacity: 10874 },
  sukru_saracoglu: { id: "st-sukru-saracoglu", slug: "sukru-saracoglu", name: "Fenerbahçe Şükrü Saracoğlu Spor Kompleksi", city: "Istanbul", country: "Turkey", capacity: 47911 },
  viking_stadion: { id: "st-viking-stadion", slug: "viking-stadion", name: "Viking stadion", city: "Stavanger", country: "Norway", capacity: 14538 },
  villa_park: { id: "st-villa-park", slug: "villa-park", name: "Villa Park", city: "Birmingham", country: "England", capacity: 28462 },

  // UEFA Europa League 2026/27 venues not already covered above. Same
  // provenance and the same caveats: UEFA's own record for these fixtures,
  // sponsor-free names, and UEFA's capacity rather than the domestic one.
  anderlecht_stadium: { id: "st-anderlecht", slug: "rsc-anderlecht-stadium", name: "RSC Anderlecht Stadium", city: "Brussels", country: "Belgium", capacity: 19370 },
  anoeta: { id: "st-anoeta", slug: "estadio-de-anoeta", name: "Estadio de Anoeta", city: "San Sebastián", country: "Spain", capacity: 39313 },
  arasen: { id: "st-arasen", slug: "arasen", name: "Åråsen", city: "Lillestrøm", country: "Norway", capacity: 9076 },
  az_stadion: { id: "st-az-stadion", slug: "az-stadion", name: "AZ Stadion", city: "Alkmaar", country: "Netherlands", capacity: 19000 },
  balaidos: { id: "st-balaidos", slug: "estadio-balaidos", name: "Estadio Balaídos", city: "Vigo", country: "Spain", capacity: 23373 },
  bayarena: { id: "st-bayarena", slug: "bayarena", name: "BayArena", city: "Leverkusen", country: "Germany", capacity: 25343 },
  benfica_estadio: { id: "st-benfica", slug: "estadio-do-sl-benfica", name: "Estádio do SL Benfica", city: "Lisbon", country: "Portugal", capacity: 68118 },
  besiktas_stadium: { id: "st-besiktas", slug: "besiktas-stadium", name: "Beşiktaş Stadium", city: "Istanbul", country: "Turkey", capacity: 42445 },
  bialystok_municipal: { id: "st-bialystok", slug: "municipal-stadium-bialystok", name: "Municipal Stadium in Białystok", city: "Białystok", country: "Poland", capacity: 22172 },
  bournemouth_stadium: { id: "st-bournemouth", slug: "bournemouth-stadium", name: "Bournemouth Stadium", city: "Bournemouth", country: "England", capacity: 9307 },
  celtic_park: { id: "st-celtic-park", slug: "celtic-park", name: "Celtic Park", city: "Glasgow", country: "Scotland", capacity: 56172 },
  den_dreef: { id: "st-den-dreef", slug: "den-dreef", name: "Den Dreef", city: "Leuven", country: "Belgium", capacity: 9806 },
  dusseldorf_arena: { id: "st-dusseldorf-arena", slug: "dusseldorf-arena", name: "Düsseldorf Arena", city: "Düsseldorf", country: "Germany", capacity: 44559 },
  ferencvaros_stadion: { id: "st-ferencvaros", slug: "ferencvaros-stadion", name: "Ferencváros Stadion", city: "Budapest", country: "Hungary", capacity: 22122 },
  giulesti: { id: "st-giulesti", slug: "giulesti-stadium", name: "Giuleşti Stadium", city: "Bucharest", country: "Romania", capacity: 14054 },
  goffertstadion: { id: "st-goffertstadion", slug: "goffertstadion", name: "Goffertstadion", city: "Nijmegen", country: "Netherlands", capacity: 11225 },
  graz_liebenau: { id: "st-graz-liebenau", slug: "stadium-graz-liebenau", name: "Stadium Graz Liebenau", city: "Graz", country: "Austria", capacity: 15323 },
  gsp: { id: "st-gsp", slug: "gsp-stadium", name: "GSP", city: "Nicosia", country: "Cyprus", capacity: 22709 },
  karaiskakis: { id: "st-karaiskakis", slug: "stadio-georgios-karaiskakis", name: "Stadio Georgios Karaiskakis", city: "Piraeus", country: "Greece", capacity: 32115 },
  leiria_municipal: { id: "st-leiria", slug: "estadio-municipal-de-leiria", name: "Estádio Municipal de Leiria - Dr. Magalhães Pessoa", city: "Leiria", country: "Portugal", capacity: 22234 },
  ol_stadium: { id: "st-ol-stadium", slug: "ol-stadium", name: "OL Stadium", city: "Décines", country: "France", capacity: 58921 },
  pankritio: { id: "st-pankritio", slug: "pankritio", name: "Pankritio", city: "Heraklion", country: "Greece", capacity: 25947 },
  plzen_mesta: { id: "st-plzen", slug: "stadion-mesta-plzne", name: "Stadion města Plzně", city: "Plzeň", country: "Czechia", capacity: 11598 },
  poznan_stadium: { id: "st-poznan", slug: "poznan-stadium", name: "Poznań Stadium", city: "Poznań", country: "Poland", capacity: 41609 },
  rhein_neckar_arena: { id: "st-rhein-neckar", slug: "rhein-neckar-arena", name: "Rhein-Neckar-Arena", city: "Sinsheim", country: "Germany", capacity: 22182 },
  roazhon_park: { id: "st-roazhon-park", slug: "roazhon-park", name: "Roazhon Park", city: "Rennes", country: "France", capacity: 29171 },
  selhurst_park: { id: "st-selhurst-park", slug: "selhurst-park", name: "Selhurst Park", city: "London", country: "England", capacity: 25486 },
  stadion_celje: { id: "st-celje", slug: "stadion-celje", name: "Stadion Celje", city: "Celje", country: "Slovenia", capacity: 8079 },
  stadion_letna: { id: "st-letna", slug: "stadion-letna", name: "Stadion Letná", city: "Prague", country: "Czechia", capacity: 18265 },
  stadion_maksimir: { id: "st-maksimir", slug: "stadion-maksimir", name: "Stadion Maksimir", city: "Zagreb", country: "Croatia", capacity: 25051 },
  stadion_salzburg: { id: "st-stadion-salzburg", slug: "stadion-salzburg", name: "Stadion Salzburg", city: "Salzburg", country: "Austria", capacity: 30071 },
  stadium_of_light: { id: "st-stadium-of-light", slug: "stadium-of-light", name: "Stadium of Light", city: "Sunderland", country: "England", capacity: 48707 },
  vasil_levski: { id: "st-vasil-levski", slug: "vasil-levski-national-stadium", name: "Natsionalen Stadion Vasil Levski", city: "Sofia", country: "Bulgaria", capacity: 43230 },
  vazgen_sargsyan: { id: "st-vazgen-sargsyan", slug: "vazgen-sargsyan-republican-stadium", name: "Republican Stadium after Vazgen Sargsyan", city: "Yerevan", country: "Armenia", capacity: 14527 },
};

export const clubs: Record<string, Club> = {
  afc_bournemouth: { id: "c-afcbournemouth", slug: "afc-bournemouth", name: "AFC Bournemouth", shortName: "Bournemouth", city: "Bournemouth", country: "England", logo: "" },
  aston_villa: { id: "c-astonvilla", slug: "aston-villa", name: "Aston Villa", shortName: "Aston Villa", city: "Birmingham", country: "England", logo: "" },
  brentford: { id: "c-brentford", slug: "brentford", name: "Brentford", shortName: "Brentford", city: "London", country: "England", logo: "" },
  brighton: { id: "c-brighton", slug: "brighton-hove-albion", name: "Brighton & Hove Albion", shortName: "Brighton", city: "Brighton", country: "England", logo: "" },
  coventry: { id: "c-coventry", slug: "coventry-city", name: "Coventry City", shortName: "Coventry", city: "Coventry", country: "England", logo: "" },
  crystal_palace: { id: "c-crystalpalace", slug: "crystal-palace", name: "Crystal Palace", shortName: "Crystal Palace", city: "London", country: "England", logo: "" },
  everton: { id: "c-everton", slug: "everton", name: "Everton", shortName: "Everton", city: "Liverpool", country: "England", logo: "" },
  fulham: { id: "c-fulham", slug: "fulham", name: "Fulham", shortName: "Fulham", city: "London", country: "England", logo: "" },
  hull: { id: "c-hull", slug: "hull-city", name: "Hull City", shortName: "Hull City", city: "Hull", country: "England", logo: "" },
  ipswich: { id: "c-ipswich", slug: "ipswich-town", name: "Ipswich Town", shortName: "Ipswich", city: "Ipswich", country: "England", logo: "" },
  leeds: { id: "c-leeds", slug: "leeds-united", name: "Leeds United", shortName: "Leeds", city: "Leeds", country: "England", logo: "" },
  nottingham_forest: { id: "c-nottinghamforest", slug: "nottingham-forest", name: "Nottingham Forest", shortName: "Forest", city: "Nottingham", country: "England", logo: "" },
  sunderland: { id: "c-sunderland", slug: "sunderland", name: "Sunderland", shortName: "Sunderland", city: "Sunderland", country: "England", logo: "" },
  arsenal: { id: "c-arsenal", slug: "arsenal", name: "Arsenal", shortName: "Arsenal", city: "London", country: "England", logo: "" },
  chelsea: { id: "c-chelsea", slug: "chelsea", name: "Chelsea", shortName: "Chelsea", city: "London", country: "England", logo: "" },
  liverpool: { id: "c-liverpool", slug: "liverpool", name: "Liverpool", shortName: "Liverpool", city: "Liverpool", country: "England", logo: "" },
  man_city: { id: "c-mancity", slug: "manchester-city", name: "Manchester City", shortName: "Man City", city: "Manchester", country: "England", logo: "" },
  man_utd: { id: "c-manutd", slug: "manchester-united", name: "Manchester United", shortName: "Man United", city: "Manchester", country: "England", logo: "" },
  tottenham: { id: "c-tottenham", slug: "tottenham-hotspur", name: "Tottenham Hotspur", shortName: "Tottenham", city: "London", country: "England", logo: "" },
  newcastle: { id: "c-newcastle", slug: "newcastle-united", name: "Newcastle United", shortName: "Newcastle", city: "Newcastle", country: "England", logo: "" },
  alaves: { id: "c-alaves", slug: "deportivo-alaves", name: "Deportivo Alavés", shortName: "Alavés", city: "Vitoria-Gasteiz", country: "Spain", logo: "" },
  athletic: { id: "c-athletic", slug: "athletic-club", name: "Athletic Club", shortName: "Athletic", city: "Bilbao", country: "Spain", logo: "" },
  betis: { id: "c-betis", slug: "real-betis", name: "Real Betis", shortName: "Betis", city: "Seville", country: "Spain", logo: "" },
  celta: { id: "c-celta", slug: "celta-vigo", name: "RC Celta de Vigo", shortName: "Celta", city: "Vigo", country: "Spain", logo: "" },
  deportivo: { id: "c-deportivo", slug: "deportivo-la-coruna", name: "RC Deportivo de La Coruña", shortName: "Deportivo", city: "A Coruña", country: "Spain", logo: "" },
  elche: { id: "c-elche", slug: "elche", name: "Elche CF", shortName: "Elche", city: "Elche", country: "Spain", logo: "" },
  espanyol: { id: "c-espanyol", slug: "espanyol", name: "RCD Espanyol", shortName: "Espanyol", city: "Barcelona", country: "Spain", logo: "" },
  getafe: { id: "c-getafe", slug: "getafe", name: "Getafe CF", shortName: "Getafe", city: "Getafe", country: "Spain", logo: "" },
  levante: { id: "c-levante", slug: "levante", name: "Levante UD", shortName: "Levante", city: "Valencia", country: "Spain", logo: "" },
  malaga: { id: "c-malaga", slug: "malaga", name: "Málaga CF", shortName: "Málaga", city: "Málaga", country: "Spain", logo: "" },
  osasuna: { id: "c-osasuna", slug: "osasuna", name: "CA Osasuna", shortName: "Osasuna", city: "Pamplona", country: "Spain", logo: "" },
  rayo: { id: "c-rayo", slug: "rayo-vallecano", name: "Rayo Vallecano", shortName: "Rayo", city: "Madrid", country: "Spain", logo: "" },
  racing: { id: "c-racing", slug: "racing-santander", name: "Real Racing Club de Santander", shortName: "Racing", city: "Santander", country: "Spain", logo: "" },
  real_sociedad: { id: "c-realsociedad", slug: "real-sociedad", name: "Real Sociedad", shortName: "Real Sociedad", city: "San Sebastián", country: "Spain", logo: "" },
  sevilla: { id: "c-sevilla", slug: "sevilla", name: "Sevilla FC", shortName: "Sevilla", city: "Seville", country: "Spain", logo: "" },
  valencia: { id: "c-valencia", slug: "valencia", name: "Valencia CF", shortName: "Valencia", city: "Valencia", country: "Spain", logo: "" },
  villarreal: { id: "c-villarreal", slug: "villarreal", name: "Villarreal CF", shortName: "Villarreal", city: "Villarreal", country: "Spain", logo: "" },
  real_madrid: { id: "c-realmadrid", slug: "real-madrid", name: "Real Madrid", shortName: "Real Madrid", city: "Madrid", country: "Spain", logo: "" },
  barcelona: { id: "c-barcelona", slug: "barcelona", name: "FC Barcelona", shortName: "Barcelona", city: "Barcelona", country: "Spain", logo: "" },
  atletico: { id: "c-atletico", slug: "atletico-madrid", name: "Atlético de Madrid", shortName: "Atlético", city: "Madrid", country: "Spain", logo: "" },
  atalanta: { id: "c-atalanta", slug: "atalanta", name: "Atalanta BC", shortName: "Atalanta", city: "Bergamo", country: "Italy", logo: "" },
  bologna: { id: "c-bologna", slug: "bologna", name: "Bologna FC", shortName: "Bologna", city: "Bologna", country: "Italy", logo: "" },
  cagliari: { id: "c-cagliari", slug: "cagliari", name: "Cagliari Calcio", shortName: "Cagliari", city: "Cagliari", country: "Italy", logo: "" },
  como: { id: "c-como", slug: "como", name: "Como 1907", shortName: "Como", city: "Como", country: "Italy", logo: "" },
  fiorentina: { id: "c-fiorentina", slug: "fiorentina", name: "ACF Fiorentina", shortName: "Fiorentina", city: "Florence", country: "Italy", logo: "" },
  frosinone: { id: "c-frosinone", slug: "frosinone", name: "Frosinone Calcio", shortName: "Frosinone", city: "Frosinone", country: "Italy", logo: "" },
  genoa: { id: "c-genoa", slug: "genoa", name: "Genoa CFC", shortName: "Genoa", city: "Genoa", country: "Italy", logo: "" },
  lazio: { id: "c-lazio", slug: "lazio", name: "SS Lazio", shortName: "Lazio", city: "Rome", country: "Italy", logo: "" },
  lecce: { id: "c-lecce", slug: "lecce", name: "US Lecce", shortName: "Lecce", city: "Lecce", country: "Italy", logo: "" },
  monza: { id: "c-monza", slug: "monza", name: "AC Monza", shortName: "Monza", city: "Monza", country: "Italy", logo: "" },
  parma: { id: "c-parma", slug: "parma", name: "Parma Calcio", shortName: "Parma", city: "Parma", country: "Italy", logo: "" },
  sassuolo: { id: "c-sassuolo", slug: "sassuolo", name: "US Sassuolo", shortName: "Sassuolo", city: "Sassuolo", country: "Italy", logo: "" },
  torino: { id: "c-torino", slug: "torino", name: "Torino FC", shortName: "Torino", city: "Turin", country: "Italy", logo: "" },
  udinese: { id: "c-udinese", slug: "udinese", name: "Udinese Calcio", shortName: "Udinese", city: "Udine", country: "Italy", logo: "" },
  venezia: { id: "c-venezia", slug: "venezia", name: "Venezia FC", shortName: "Venezia", city: "Venice", country: "Italy", logo: "" },
  inter: { id: "c-inter", slug: "inter-milan", name: "Inter Milan", shortName: "Inter", city: "Milan", country: "Italy", logo: "" },
  ac_milan: { id: "c-acmilan", slug: "ac-milan", name: "AC Milan", shortName: "AC Milan", city: "Milan", country: "Italy", logo: "" },
  juventus: { id: "c-juventus", slug: "juventus", name: "Juventus FC", shortName: "Juventus", city: "Turin", country: "Italy", logo: "" },
  napoli: { id: "c-napoli", slug: "napoli", name: "SSC Napoli", shortName: "Napoli", city: "Naples", country: "Italy", logo: "" },
  roma: { id: "c-roma", slug: "as-roma", name: "AS Roma", shortName: "Roma", city: "Rome", country: "Italy", logo: "" },
  bayern: { id: "c-bayern", slug: "bayern-munich", name: "FC Bayern München", shortName: "Bayern", city: "Munich", country: "Germany", logo: "" },
  dortmund: { id: "c-dortmund", slug: "borussia-dortmund", name: "Borussia Dortmund", shortName: "Dortmund", city: "Dortmund", country: "Germany", logo: "" },
  leipzig: { id: "c-leipzig", slug: "rb-leipzig", name: "RB Leipzig", shortName: "Leipzig", city: "Leipzig", country: "Germany", logo: "" },
  auxerre: { id: "c-auxerre", slug: "auxerre", name: "AJ Auxerre", shortName: "Auxerre", city: "Auxerre", country: "France", logo: "" },
  angers: { id: "c-angers", slug: "angers", name: "Angers SCO", shortName: "Angers", city: "Angers", country: "France", logo: "" },
  brest: { id: "c-brest", slug: "brest", name: "Stade Brestois 29", shortName: "Brest", city: "Brest", country: "France", logo: "" },
  lorient: { id: "c-lorient", slug: "lorient", name: "FC Lorient", shortName: "Lorient", city: "Lorient", country: "France", logo: "" },
  le_havre: { id: "c-lehavre", slug: "le-havre", name: "Le Havre AC", shortName: "Le Havre", city: "Le Havre", country: "France", logo: "" },
  le_mans: { id: "c-lemans", slug: "le-mans", name: "Le Mans FC", shortName: "Le Mans", city: "Le Mans", country: "France", logo: "" },
  lille: { id: "c-lille", slug: "lille", name: "LOSC Lille", shortName: "Lille", city: "Lille", country: "France", logo: "" },
  nice: { id: "c-nice", slug: "nice", name: "OGC Nice", shortName: "Nice", city: "Nice", country: "France", logo: "" },
  lyon: { id: "c-lyon", slug: "lyon", name: "Olympique Lyonnais", shortName: "Lyon", city: "Lyon", country: "France", logo: "" },
  paris_fc: { id: "c-parisfc", slug: "paris-fc", name: "Paris FC", shortName: "Paris FC", city: "Paris", country: "France", logo: "" },
  lens: { id: "c-lens", slug: "lens", name: "RC Lens", shortName: "Lens", city: "Lens", country: "France", logo: "" },
  rennes: { id: "c-rennes", slug: "rennes", name: "Stade Rennais FC", shortName: "Rennes", city: "Rennes", country: "France", logo: "" },
  strasbourg: { id: "c-strasbourg", slug: "strasbourg", name: "RC Strasbourg Alsace", shortName: "Strasbourg", city: "Strasbourg", country: "France", logo: "" },
  toulouse: { id: "c-toulouse", slug: "toulouse", name: "Toulouse FC", shortName: "Toulouse", city: "Toulouse", country: "France", logo: "" },
  troyes: { id: "c-troyes", slug: "troyes", name: "ESTAC Troyes", shortName: "Troyes", city: "Troyes", country: "France", logo: "" },
  koeln: { id: "c-koeln", slug: "koeln", name: "1. FC Köln", shortName: "Köln", city: "Cologne", country: "Germany", logo: "" },
  union_berlin: { id: "c-unionberlin", slug: "union-berlin", name: "1. FC Union Berlin", shortName: "Union Berlin", city: "Berlin", country: "Germany", logo: "" },
  mainz: { id: "c-mainz", slug: "mainz", name: "1. FSV Mainz 05", shortName: "Mainz", city: "Mainz", country: "Germany", logo: "" },
  leverkusen: { id: "c-leverkusen", slug: "leverkusen", name: "Bayer 04 Leverkusen", shortName: "Leverkusen", city: "Leverkusen", country: "Germany", logo: "" },
  gladbach: { id: "c-gladbach", slug: "borussia-monchengladbach", name: "Borussia Mönchengladbach", shortName: "Gladbach", city: "Mönchengladbach", country: "Germany", logo: "" },
  frankfurt: { id: "c-frankfurt", slug: "eintracht-frankfurt", name: "Eintracht Frankfurt", shortName: "Frankfurt", city: "Frankfurt", country: "Germany", logo: "" },
  augsburg: { id: "c-augsburg", slug: "augsburg", name: "FC Augsburg", shortName: "Augsburg", city: "Augsburg", country: "Germany", logo: "" },
  schalke: { id: "c-schalke", slug: "schalke-04", name: "FC Schalke 04", shortName: "Schalke", city: "Gelsenkirchen", country: "Germany", logo: "" },
  hamburg: { id: "c-hamburg", slug: "hamburger-sv", name: "Hamburger SV", shortName: "Hamburg", city: "Hamburg", country: "Germany", logo: "" },
  paderborn: { id: "c-paderborn", slug: "paderborn", name: "SC Paderborn 07", shortName: "Paderborn", city: "Paderborn", country: "Germany", logo: "" },
  freiburg: { id: "c-freiburg", slug: "freiburg", name: "SC Freiburg", shortName: "Freiburg", city: "Freiburg", country: "Germany", logo: "" },
  elversberg: { id: "c-elversberg", slug: "elversberg", name: "SV Elversberg", shortName: "Elversberg", city: "Spiesen-Elversberg", country: "Germany", logo: "" },
  werder: { id: "c-werder", slug: "werder-bremen", name: "SV Werder Bremen", shortName: "Werder", city: "Bremen", country: "Germany", logo: "" },
  hoffenheim: { id: "c-hoffenheim", slug: "hoffenheim", name: "TSG Hoffenheim", shortName: "Hoffenheim", city: "Sinsheim", country: "Germany", logo: "" },
  stuttgart: { id: "c-stuttgart", slug: "stuttgart", name: "VfB Stuttgart", shortName: "Stuttgart", city: "Stuttgart", country: "Germany", logo: "" },
  psg: { id: "c-psg", slug: "paris-saint-germain", name: "Paris Saint-Germain", shortName: "PSG", city: "Paris", country: "France", logo: "" },
  marseille: { id: "c-marseille", slug: "marseille", name: "Olympique de Marseille", shortName: "Marseille", city: "Marseille", country: "France", logo: "" },
  monaco: { id: "c-monaco", slug: "monaco", name: "AS Monaco", shortName: "Monaco", city: "Monaco", country: "Monaco", logo: "" },

  // UEFA Champions League 2026/27 — the league-phase clubs that play in no
  // domestic league Seatigo covers. The other 21 participants are already
  // above and keep their existing ids, so Arsenal is one club across the
  // Premier League and the Champions League, not two.
  //
  // `city` is the club's own home city. Shakhtar's is Donetsk even though
  // UEFA has them playing their home ties in London — the venue decides
  // where a fixture is, the club record does not.
  aek_athens: { id: "c-aekathens", slug: "aek-athens", name: "AEK Athens FC", shortName: "AEK", city: "Athens", country: "Greece", logo: "" },
  bodo_glimt: { id: "c-bodoglimt", slug: "bodo-glimt", name: "FK Bodø/Glimt", shortName: "Bodø/Glimt", city: "Bodø", country: "Norway", logo: "" },
  club_brugge: { id: "c-clubbrugge", slug: "club-brugge", name: "Club Brugge KV", shortName: "Club Brugge", city: "Bruges", country: "Belgium", logo: "" },
  fenerbahce: { id: "c-fenerbahce", slug: "fenerbahce", name: "Fenerbahçe SK", shortName: "Fenerbahçe", city: "Istanbul", country: "Turkey", logo: "" },
  feyenoord: { id: "c-feyenoord", slug: "feyenoord", name: "Feyenoord", shortName: "Feyenoord", city: "Rotterdam", country: "Netherlands", logo: "" },
  galatasaray: { id: "c-galatasaray", slug: "galatasaray", name: "Galatasaray A.Ş.", shortName: "Galatasaray", city: "Istanbul", country: "Turkey", logo: "" },
  lask: { id: "c-lask", slug: "lask", name: "LASK", shortName: "LASK", city: "Linz", country: "Austria", logo: "" },
  porto: { id: "c-porto", slug: "porto", name: "FC Porto", shortName: "Porto", city: "Porto", country: "Portugal", logo: "" },
  psv: { id: "c-psv", slug: "psv-eindhoven", name: "PSV Eindhoven", shortName: "PSV", city: "Eindhoven", country: "Netherlands", logo: "" },
  sabah: { id: "c-sabah", slug: "sabah", name: "Sabah FC", shortName: "Sabah", city: "Baku", country: "Azerbaijan", logo: "" },
  shakhtar: { id: "c-shakhtar", slug: "shakhtar-donetsk", name: "FC Shakhtar Donetsk", shortName: "Shakhtar", city: "Donetsk", country: "Ukraine", logo: "" },
  slavia_praha: { id: "c-slaviapraha", slug: "slavia-praha", name: "SK Slavia Praha", shortName: "Slavia Praha", city: "Prague", country: "Czechia", logo: "" },
  slovan_bratislava: { id: "c-slovanbratislava", slug: "slovan-bratislava", name: "ŠK Slovan Bratislava", shortName: "Slovan", city: "Bratislava", country: "Slovakia", logo: "" },
  sporting_cp: { id: "c-sportingcp", slug: "sporting-cp", name: "Sporting Clube de Portugal", shortName: "Sporting CP", city: "Lisbon", country: "Portugal", logo: "" },
  viking: { id: "c-viking", slug: "viking", name: "Viking FK", shortName: "Viking", city: "Stavanger", country: "Norway", logo: "" },

  // UEFA Europa League 2026/27 — the 24 league-phase clubs that play in no
  // domestic league Seatigo covers and were not already added for the
  // Champions League. The other 12 participants reuse their existing
  // records, so Milan, Juventus and Marseille are one club each across
  // their domestic league and Europe.
  //
  // As with Shakhtar, `city` is the club's own home city even when UEFA has
  // them hosting elsewhere: Hapoel Beer-Sheva stay a Be'er Sheva club while
  // playing their home ties in Bucharest.
  anderlecht: { id: "c-anderlecht", slug: "anderlecht", name: "RSC Anderlecht", shortName: "Anderlecht", city: "Brussels", country: "Belgium", logo: "" },
  ararat_armenia: { id: "c-araratarmenia", slug: "ararat-armenia", name: "FC Ararat-Armenia", shortName: "Ararat-Armenia", city: "Yerevan", country: "Armenia", logo: "" },
  az_alkmaar: { id: "c-azalkmaar", slug: "az-alkmaar", name: "AZ Alkmaar", shortName: "AZ", city: "Alkmaar", country: "Netherlands", logo: "" },
  benfica: { id: "c-benfica", slug: "benfica", name: "SL Benfica", shortName: "Benfica", city: "Lisbon", country: "Portugal", logo: "" },
  besiktas: { id: "c-besiktas", slug: "besiktas", name: "Beşiktaş JK", shortName: "Beşiktaş", city: "Istanbul", country: "Turkey", logo: "" },
  celje: { id: "c-celje", slug: "celje", name: "NK Celje", shortName: "Celje", city: "Celje", country: "Slovenia", logo: "" },
  celtic: { id: "c-celtic", slug: "celtic", name: "Celtic FC", shortName: "Celtic", city: "Glasgow", country: "Scotland", logo: "" },
  dinamo_zagreb: { id: "c-dinamozagreb", slug: "dinamo-zagreb", name: "GNK Dinamo Zagreb", shortName: "Dinamo", city: "Zagreb", country: "Croatia", logo: "" },
  ferencvaros: { id: "c-ferencvaros", slug: "ferencvaros", name: "Ferencvárosi TC", shortName: "Ferencváros", city: "Budapest", country: "Hungary", logo: "" },
  hapoel_beer_sheva: { id: "c-hapoelbeersheva", slug: "hapoel-beer-sheva", name: "Hapoel Beer-Sheva FC", shortName: "Hapoel B-S", city: "Be'er Sheva", country: "Israel", logo: "" },
  jagiellonia: { id: "c-jagiellonia", slug: "jagiellonia-bialystok", name: "Jagiellonia Białystok", shortName: "Jagiellonia", city: "Białystok", country: "Poland", logo: "" },
  lech_poznan: { id: "c-lechpoznan", slug: "lech-poznan", name: "KKS Lech Poznań", shortName: "Lech Poznań", city: "Poznań", country: "Poland", logo: "" },
  levski_sofia: { id: "c-levskisofia", slug: "levski-sofia", name: "PFC Levski Sofia", shortName: "Levski", city: "Sofia", country: "Bulgaria", logo: "" },
  lillestrom: { id: "c-lillestrom", slug: "lillestrom", name: "Lillestrøm SK", shortName: "Lillestrøm", city: "Lillestrøm", country: "Norway", logo: "" },
  nec_nijmegen: { id: "c-necnijmegen", slug: "nec-nijmegen", name: "N.E.C. Nijmegen", shortName: "NEC", city: "Nijmegen", country: "Netherlands", logo: "" },
  ofi_crete: { id: "c-oficrete", slug: "ofi-crete", name: "OFI Crete FC", shortName: "OFI", city: "Heraklion", country: "Greece", logo: "" },
  olympiacos: { id: "c-olympiacos", slug: "olympiacos", name: "Olympiacos FC", shortName: "Olympiacos", city: "Piraeus", country: "Greece", logo: "" },
  omonia: { id: "c-omonia", slug: "omonia", name: "Omonia FC", shortName: "Omonia", city: "Nicosia", country: "Cyprus", logo: "" },
  salzburg: { id: "c-salzburg", slug: "salzburg", name: "FC Salzburg", shortName: "Salzburg", city: "Salzburg", country: "Austria", logo: "" },
  sparta_praha: { id: "c-spartapraha", slug: "sparta-praha", name: "AC Sparta Praha", shortName: "Sparta Praha", city: "Prague", country: "Czechia", logo: "" },
  sturm_graz: { id: "c-sturmgraz", slug: "sturm-graz", name: "SK Sturm Graz", shortName: "Sturm Graz", city: "Graz", country: "Austria", logo: "" },
  torreense: { id: "c-torreense", slug: "torreense", name: "SCU Torreense", shortName: "Torreense", city: "Torres Vedras", country: "Portugal", logo: "" },
  union_saint_gilloise: { id: "c-unionsg", slug: "union-saint-gilloise", name: "R. Union Saint-Gilloise", shortName: "Union SG", city: "Brussels", country: "Belgium", logo: "" },
  viktoria_plzen: { id: "c-viktoriaplzen", slug: "viktoria-plzen", name: "FC Viktoria Plzeň", shortName: "Viktoria Plzeň", city: "Plzeň", country: "Czechia", logo: "" },
};
